# Keep it simple {#simple}


The most straight forward way to achieve explainable machine learning algorithms is to use only a subset algorithms that yield an understandable model structure.

These are:

* linear models
* trees
* rules

In the following chapters these we will talk about the algorithm with it's variants. Not in detail, only the basics, because there are already a ton of books, videos, tutorials, papers and so on about them. We will focus on how to interpret the models and why they are explainable.
The chapter covers linear models, decision trees, decision rules, neighbour methods and graphical models.

## Overview

| Algorithm |Linear |Monotonicity |Interaction built-in |
|:--------------|:----|:----|:------|
| Linear models | Yes | Yes | No |
| Decision trees | No | Not by default | Yes |
| Decision rules | No | Not by default | Yes |
| Naive bayes | Yes | Yes | No |
| Nearest neighbours | No | No | No |
## Linear models

Linear models have been and are still used by statistician, computer scientists and other people with quantitative problems. They learn straightforward linear (and monotonic) relationships between the target and the features. The target changes by a learned weight depending on the feature. Monotonicity makes the interpretation easy.


Linear models can be used to model the dependency of a regression variable (here Y) on K covariates. As the name says, the learned relationships are linear in the form of

$$y_{i} = \beta_{0} + \beta_{1} \cdot x_{i,1} + \ldots + \beta_{K} x_{i,K} + \epsilon_{i}$$

The i-th observation's outcome is a weighted sum of it's K features. The $\beta_{k}$ represent the learned feature weights or coefficients. The $\epsilon_{i}$ is the error we are still making, the difference between the predicted and actual outcome.

The biggest advantage is the linearity: It makes the estimation procedure straight forward and most importantly these linear equations have an easy to understand interpretation. That is one of the main reasons why the linear model and all it's descendants are so widespread in academic fields like medicine, sociology, psychology and many more quantitative research fields. In this areas it is important to not only predict e.g. the clinical outcome of a patient, but also quantify the influence of the medication while at the same time accounting for things like sex, age and other variables.

### Interpretation
The interpretation of the coefficients:

- Continuous regression variable: For an increase of one point of the variable $x_{j}$ the estimated outcome changes by $\beta_{j}$
- Binary categorial variables: One of the variables is the reference level (in some languages the one that was coded in 0). A change of the variable $x_{i}$ the reference level to the other category changes the estimated outcome by $\beta_{i}$
- Categorial variables with many levels: One solution to deal with many variables is to one-hot-encode them, meaning each level gets it's own column. From a categorial variable with L levels, you only need L-1 columsn, otherwise it is over parameterized. The interpretation for each level is then according to the binary variables. Some language like R allow to
- Intercept $\beta_{0}$: The interpretation is: Given all continuous variables are zero and the categorial variables are on the reference level, the estimated outcome of $y_{i}$ is $\beta_{0}$. The interpretation of $\beta_{0}$ is usually not relevant.

### Interpretation example

```{r echo=FALSE,  message=FALSE}
library('mlbench')
library('knitr')
data('BostonHousing')
lm_summary = summary(lm(medv ~ ., data = BostonHousing))$coefficients[,c('Estimate', 'Std. Error')]

name_matches = c('crim'='per capita crime rate',
                 'zn'='proportion of residential land zoned for lots over 25,000 sq.ft',
                 'indus'='proportion of non-retail business acres per town',
                 'chas1'='Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)',
                 'nox'='nitric oxides concentration (parts per 10 million)',
                 'rm'='average number of rooms per dwelling',
                 'age'='proportion of owner-occupied units built prior to 1940',
                 'dis'='weighted distances to five Boston employment centres',
                 'rad'='index of accessibility to radial highways',
                 'tax'='full-value property-tax rate per USD 10,000',
                 'ptratio'='pupil-teacher ratio by town',
                 'b'='1000(B - 0.63)^2 where B is the proportion of blacks by town',
                 'lstat'='percentage of lower status of the population',
                 'medv'='median value of owner-occupied homes in USD 1000', '(Intercept)'='(Intercept)')
rownames(lm_summary) = name_matches[rownames(lm_summary)]
kable(lm_summary)
```

Interpretation of a numerical variable ('average number of rooms per dwelling'): An increase of the average number of rooms by 1 increases the median value of houses in this suburb by $3800\$ (= 3.8 \cdot 1000)$, given all other features stay the same.

Interpretation of a categorial variable ('Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)'): The median value of houses in suburbs that  bound the Charles River is $2690\$ (= 2.69 \cdot 1000\$)$ compared to houses that do not, given all other features stay the same.

As you can see in the interpretation examples, the interpretations are always coming with the clause that 'all other features stay the same'.
That's because of the nature of linear models: All features are input linearly into the function with no interactions (unless explicitly specified). The good side is, that is isolates the interpretation. If you think of the features as turn-switches that you can turn up or down, it is nice to see what happens when you would just turn the switch for one feature, for example the average number of rooms. But this might not reflect the structure of the data, because the features are often correlated. It might not be meaningful to see the effect of turning up average room sizes because it might be strongly correlated with the proportion of owner-occupied units built prior to 1940.

### Interpretation templates

**Interpretation of a numerical feature**:

An increase of $x_{k}$ by one unit increases the expectation for $y$ by $\beta_x{k}$ units if all other features X stay the same.

**Interpretation of a categorial feature**:

The category coded with 1 of $x_{k}$ increases the expectation for $y$ by $\beta_{k}$ compared to the reference category (coded with 0).


### Coding categorial variables:
There are several ways to represent a categorial variable, which has an influence on the interpretation: http://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/ and
http://heidiseibold.github.io/page7/

Described above is the treatment coding, which is usually sufficient.
Using different codings boils down to creating different matrices from your one column with the categorial feature.
I present three different codings, but there are many more. The example has six instances and one categorial feature with 3 levels. The first two instances are in category A, instances three and four are in category B and the last two instances are in category C.

- **Treatment coding** compares each level to the reference level. The intercept is the mean of the reference group. The first column is the intercept, which is always 1. Column two is an indicator whether instance $i$ is in category B, columns three is an indicator for category C. There is no need for a column for category A, because than the system would be over specified. Knowing that an instance is neither in category B or C is enough.
$$
\begin{pmatrix}
1 & 0 & 0 \\
1 & 0 & 0 \\
1 & 1 & 0 \\
1 & 1 & 0 \\
1 & 0 & 1 \\
1 & 0 & 1 \\
\end{pmatrix}
$$
- **Effect coding** compares each level to the overall mean of $y$. The first column is again the intercept. The weight $\beta_{0}$ which is associated to the intercept represents the overall mean and $\beta_{1}$, the weight for column two is the difference between the overall mean and category B. The overall effect of category B is $\beta_{0}$ + \beta_{1}$. Interpretation for category C is equivalent. For the reference category A, $-(\beta_{1} + \beta_{2})$ is the difference of the category C to the overall mean and $\beta_{0} -(\beta_{1} + \beta_{2})$ the overall effect of category C.
$$
\begin{pmatrix}
1 & -1 & -1 \\
1 & -1 & -1 \\
1 & 1 & 0 \\
1 & 1 & 0 \\
1 & 0 & 1 \\
1 & 0 & 1 \\
\end{pmatrix}
$$
- **Dummy coding** compares each level to the level mean of $y$. If all level are have the same frequency the resulting coefficients will be the same as in effect coding. Note that the intercept was dropped here.
$$
\begin{pmatrix}
1 & 0 & 0 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
0 & 0 & 1 \\
\end{pmatrix}
$$




### Explaining a single observation:

Let's look at a concrete example:

You are trying to predict the house price using the notorious Boston house prize data set. So y is the prize of the house and your X are: ...

The fitted linear model for the prize comes down to the following equation:

EQUATION


### The disadvantages of linear models
They can only represent linear relationships as the name suggests. Each non-linearity or interaction has to be hand-crafted and explicitly given to the model as an input feature.
Because of possible high correlation between features, it is possible that a feature that is positively correlated with the outcome might get a negative weight in a linear model, because in the high dimensional space it is negatively correlated. An example: You have a model to predict the rent price and have features like number of rooms and size of the flat. Of course flat size and room number are highly correlated, the bigger a flat the more rooms it has. If you now take both variables into a linear model it might happen, that the flat size is the better predictor and get's a large positive weight. The room number might end up getting a negative weight, because given that a flat has the same size, increasing the number of rooms could make it less valuable.  


### Towards complexer relationships within linear model class
- Adding interactions
- Adding non-linear terms like polynomials
- Stratifying data by variable and fitting linear models on subsets

### Linear models beyond gaussian regression
- Logistic regression
- Lasso, Ridge, elasticnet
- GAMs
- Quantile regression


## Decision trees
### Explaining: Treeinterpreter
https://github.com/andosa/treeinterpreter
## RuleFit
## Decision rules
## Decision tables
## Nearest neighbours
### Learning deep k-nearest neighbour representations
## Bayesian network classifiers
## Naive Bayes Classifier and other graphical models
### Naive bayes
Good in case you want interpretation of all features. Bad: No interaction, but even strong assumption of independence of features given the class. But if you indeed have independent features, then it might be the best model.

### More general bayesian network approache(s)
#### Bayesian Network-Augmented Naïve Bayes (BAN) illustrated
#### General Bayesian Network



## Interpretation overview
INSERT HERE: One example of classification task and one for regression task plus for each a table with the interpretations per model (maybe only example for one variable). Plus verbal template for each interpretation.

## Monotonicity constraints between features
