## What to Expect from This Book
This book will teach you how to make (supervised) machine learning models interpretable.
It contains one or the other mathematical formula, but it's kept at a manageable level of math.
This book is not for people who are trying to learn machine learning from scratch.
If you are new to machine learning, there are loads of books and other resources for learning the basics.
I recommend the book [Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/) from @Hastie2009 and [Andrew Ng's "Machine Learning" online course on coursera](https://www.coursera.org/learn/machine-learning) to get started with machine learning.
Both the book and the course are available for free!
  
This book starts with some short stories in Chapter \@ref(storytime), which are not required to understand the book, but hopefully entertaining!
The book explores the concepts of machine learning interpretability in Chapter \@ref(interpretability):
It reveals when interpretability is important and discusses different types of explanations.
Definitions used throughout the book can be looked up in Chapter \@ref(definitions).
All models and methods are explained and demonstrated with real data examples from Chapter \@ref(data).
One way to make machine learning interpretable is by using interpretable models, like linear models or decision trees.
Interpretable models are introduced in Chapter \@ref(simple).
The other option is to use model-agnostic interpretability methods, which are the topic of Chapter \@ref(agnostic).
This chapter covers methods like partial dependence plots and permutation feature importance.
Model-agnostic methods work by changing the input of the machine learning model and measuring changes in the output.

You can either read the book from start to end or directly jump to the methods you are interested in.
I hope you will enjoy the read!
