# Model-Specific Methods {#example-based}

Interpretation methods that are model-specific only work for a special class of machine learning models and require access to the parameters of the model (e.g. the weights) or influences the training process.

- blurry line between model-specific method and interpretable model. interpreting parameters can be seen as model-specific interpretation method.
- here, model-specific more if a lot more complex, but I acknowledge that it is not clear cut.


Two distictions:
- during training, e.g. fit only monotonic relationships
- after training, e.g. interpretation of neurons

can be more powerful than model-agnostic methods, since access to the model and therefore insight or influence in the mechanism that actually makes the predictions.

This chapter is used a bit different than the model-agnostic chapter.
Here we focus on the type of model / task and then have a chapter for it.


The chapters in this part cover model-specific interpretation methods for the following models / tasks (at least what I have collected so far):

<!--TODO: Write a short sentence for each, as in model-agnostic or example-based -->




- Neural Networks
  - Convolutional Neural Networks - Feature Visualization
  - Convolutional Neural Networks - Feature Attribution (DeepExplainer, GradientExplainer, Integrated Gradients (IG), LRP, DeepLift, also for tabular and text data)
  - TCAV (Testing with Concept Activation Vectors) https://arxiv.org/abs/1711.11279 and https://github.com/tensorflow/tcav  
  - RNNs attention http://karpathy.github.io/2015/05/21/rnn-effectiveness/
  - Grad CAM  - https://arxiv.org/abs/1610.02391
  - class activation maps - https://jacobgil.github.io/deeplearning/class-activation-maps
- Tree Ensembles
  - Random Forests and other tree ensembles: https://cran.r-project.org/web/packages/inTrees/index.html, 
  - Boosting - Monotonicity constraints, https://github.com/IBCNServices/GENESIM
- Survival analysis
- Recommender systems
- Multinomial Regression?
- Clustering?
- Text classification / NLP
- Survival analysis - If you extract a single number, e.g. median survival time, you can use all model-agnostic methods, like ALE, also you can use survxai package for kaplan-meier like stuff.

