# Contribute to the Book

Thank you for reading my book about Interpretable Machine Learning.
The book is under continuous development.
It will be improved over time and more chapters will be added.
Very similar to how software is developed.

All text and code for the book is open source and [available at github.com](https://github.com/christophM/interpretable-ml-book).
On the Github page you can suggest fixes and [open issues](https://github.com/christophM/interpretable-ml-book/issues) if you find a mistake or if something is missing.

If you want to help out even more, the issues page is also the best place to find problems to fix and a good way to contribute to the book.
If you are interested in a larger contributions, please send me a message with your concrete idea: [christoph.molnar.ai@gmail.com](mailto:christoph.molnar.ai@gmail.com).



# Citing this Book

If you found this book useful for your blog post, research article or product, I would be grateful if you would cite this book.
You can cite the book like this:


    Molnar, C. (2018). Interpretable Machine Learning. Retrieved from https://christophm.github.io/interpretable-ml-book/

Or use the following bibtex entry:


    @book{molnar,
      title = {Interpretable Machine Learning},
      author = {Christoph Molnar},
      publisher = {https://christophm.github.io/interpretable-ml-book/},
      note = {\url{https://christophm.github.io/interpretable-ml-book/}},
      year = {2018}
    }


I am always curious about where and how interpretation methods are used in industry and research.
If you use the book as a reference, it would be great if you wrote me a line and told me what for. 
This is of course optional and only serves to satisfy my own curiosity and to stimulate interesting exchanges. 
My mail is christoph.molnar.ai@gmail.com .
