# A Look into the Crystal Ball {#future}

Apa masa depan interpretable machine learning?
Bab ini adalah latihan mental spekulatif dan tebakan subjektif bagaimana interpretable machine learning akan berkembang.
Saya membuka buku ini dengan [cerita pendek](#storytime) yang agak pesimis dan ingin menutupnya dengan pandangan yang lebih optimis.

Saya telah mendasarkan "prediksi" saya pada tiga premis:

1. **Digitasi: Setiap informasi (menarik) akan didigitalkan.**
Pikirkan uang elektronik dan transaksi online.
Pikirkan e-book, musik, dan video.
Pikirkan semua data sensorik tentang lingkungan kita, perilaku manusia kita, proses produksi industri dan sebagainya.
Penggerak digitalisasi segalanya adalah: Komputer/sensor/penyimpanan murah, efek penskalaan (pemenang mengambil semuanya), model bisnis baru, rantai nilai modular, tekanan biaya, dan banyak lagi.
1. **Otomasi: Ketika tugas dapat diotomatisasi dan biaya otomatisasi lebih rendah daripada biaya pelaksanaan tugas dari waktu ke waktu, tugas akan otomatis.**
Bahkan sebelum pengenalan komputer, kami memiliki tingkat otomatisasi tertentu.
Misalnya mesin tenun otomatis mesin tenun atau mesin uap tenaga kuda otomatis.
Tetapi komputer dan digitalisasi membawa otomatisasi ke tingkat berikutnya.
Fakta bahwa Anda dapat memprogram for-loop, menulis makro Excel, mengotomatiskan respons email, dan sebagainya, menunjukkan seberapa banyak yang dapat diotomatisasi oleh seseorang.
Mesin tiket mengotomatisasi pembelian tiket kereta api (tidak perlu kasir lagi), mesin cuci mengotomatisasi laundry, standing order mengotomatisasi transaksi payout dan sebagainya.
Mengotomatiskan tugas membebaskan waktu dan uang, jadi ada insentif ekonomi dan pribadi yang sangat besar untuk mengotomatisasi berbagai hal.
Kami saat ini mengamati otomatisasi terjemahan bahasa, mengemudi dan, pada tingkat kecil, bahkan penemuan ilmiah.
1. **Kesalahan spesifikasi: Kami tidak dapat menentukan tujuan dengan sempurna dengan semua batasannya.**
Pikirkan jin dalam botol yang selalu menerima keinginan Anda secara harfiah:
"Saya ingin menjadi orang terkaya di dunia!" Anda menjadi orang terkaya, tetapi sebagai efek samping mata uang yang Anda pegang jatuh karena inflasi.
"Aku ingin bahagia selama sisa hidupku!" 5 menit berikutnya kamu merasa sangat senang, lalu jin membunuhmu.
"Saya berharap untuk perdamaian dunia!" Jin membunuh semua manusia.
Kami menentukan tujuan secara salah, baik karena kami tidak mengetahui semua kendala atau karena kami tidak dapat mengukurnya.
Mari kita lihat perusahaan sebagai contoh spesifikasi tujuan yang tidak sempurna.
Sebuah perusahaan memiliki tujuan sederhana untuk mendapatkan uang bagi pemegang sahamnya.
Namun spesifikasi ini tidak menangkap tujuan yang sebenarnya dengan segala kendalanya yang sangat kami perjuangkan:
Misalnya, kami tidak menghargai perusahaan yang membunuh orang untuk menghasilkan uang, meracuni sungai, atau hanya mencetak uangnya sendiri.
Kami telah menemukan undang-undang, peraturan, sanksi, prosedur compliance, serikat pekerja, dan lainnya untuk memperbaiki spesifikasi tujuan yang tidak sempurna.
Contoh lain yang dapat Anda alami sendiri adalah
[Paperclips](http://www.decisionproblem.com/paperclips/index2.html), game di mana Anda memainkan mesin dengan tujuan menghasilkan penjepit kertas sebanyak mungkin.
PERINGATAN: Ini membuat ketagihan.
Saya tidak ingin merusaknya terlalu banyak, tetapi katakanlah hal-hal menjadi di luar kendali dengan sangat cepat.
Dalam machine learning, ketidaksempurnaan dalam spesifikasi tujuan berasal dari abstraksi data yang tidak sempurna (populasi bias, kesalahan pengukuran, ...), loss function yang tidak dibatasi, kurangnya pengetahuan tentang kendala, pergeseran distribusi antara data pelatihan dan aplikasi dan banyak lagi .

Digitalisasi mendorong otomatisasi.
Spesifikasi tujuan yang tidak sempurna bertentangan dengan otomatisasi.
Saya mengklaim bahwa konflik ini dimediasi sebagian oleh metode interpretasi.

Panggung untuk prediksi kita sudah diatur, bola kristal sudah siap, sekarang kita lihat ke mana medannya bisa pergi!


## The Future of Machine Learning

Tanpa machine learning tidak akan ada interpretable machine learning.
Oleh karena itu kita harus menebak ke mana arah machine learning sebelum kita dapat berbicara tentang interpretabilitas.

Machine learning (atau "AI") dikaitkan dengan banyak janji dan harapan.
Tapi mari kita mulai dengan pengamatan yang kurang optimis:
Sementara sains mengembangkan banyak alat machine learning yang mewah, menurut pengalaman saya, cukup sulit untuk mengintegrasikannya ke dalam proses dan produk yang ada.
Bukan karena tidak mungkin, tetapi hanya karena butuh waktu bagi perusahaan dan institusi untuk mengejar ketertinggalan.
Dalam demam emas dari hype AI saat ini, perusahaan membuka "laboratorium AI", "Unit machine learning" dan mempekerjakan "Ilmuwan Data", "Pakar machine learning", "insinyur AI", dan seterusnya, tetapi kenyataannya adalah, dalam pengalaman saya, agak frustasi.
Seringkali perusahaan bahkan tidak memiliki data dalam bentuk yang diperlukan dan para ilmuwan data menunggu selama berbulan-bulan.
Terkadang perusahaan memiliki ekspektasi tinggi terhadap AI dan Ilmu Data karena media yang tidak dapat dipenuhi oleh para ilmuwan data.
Dan seringkali tidak ada yang tahu bagaimana mengintegrasikan ilmuwan data ke dalam struktur yang ada dan banyak masalah lainnya.
Ini mengarah pada prediksi pertama saya.

**Machine learning akan berkembang perlahan tapi pasti**.

Digitalisasi semakin maju dan godaan untuk mengotomatisasi terus menarik.
Meskipun jalur adopsi machine learning lambat dan sulit, machine learning terus bergerak dari sains ke proses bisnis, produk, dan aplikasi dunia nyata.

Saya percaya kita perlu menjelaskan lebih baik kepada non-ahli jenis masalah apa yang dapat dirumuskan sebagai masalah machine learning.
Saya mengenal banyak ilmuwan data bergaji tinggi yang melakukan penghitungan Excel atau intelijen bisnis klasik dengan pelaporan dan kueri SQL alih-alih menerapkan machine learning.
Tetapi beberapa perusahaan sudah berhasil menggunakan machine learning, dengan perusahaan Internet besar di garis depan.
Kita perlu menemukan cara yang lebih baik untuk mengintegrasikan machine learning ke dalam proses dan produk, melatih orang, dan mengembangkan alat machine learning yang mudah digunakan.
Saya percaya bahwa machine learning akan menjadi lebih mudah digunakan:
Kita sudah dapat melihat bahwa machine learning menjadi lebih mudah diakses, misalnya melalui layanan cloud ("machine learning sebagai layanan" -- hanya untuk membuang beberapa kata kunci).
Setelah machine learning matang -- dan balita ini telah mengambil langkah pertamanya -- prediksi saya berikutnya adalah:

**Machine learning akan mendorong banyak hal.**

Berdasarkan prinsip "Apa pun yang dapat diotomatisasi akan diotomatisasi", saya menyimpulkan bahwa bila memungkinkan,
tugas akan dirumuskan sebagai masalah prediksi dan diselesaikan dengan machine learning.
machine learning adalah bentuk otomatisasi atau setidaknya dapat menjadi bagian darinya.
Banyak tugas yang saat ini dilakukan oleh manusia digantikan oleh machine learning.
Berikut adalah beberapa contoh tugas di mana machine learning digunakan untuk mengotomatisasi bagian-bagiannya:

- Penyortiran / pengambilan keputusan / penyelesaian dokumen (misalnya di perusahaan asuransi, sektor hukum atau perusahaan konsultan)
- Keputusan berdasarkan data seperti aplikasi kredit
- Penemuan obat
- Kontrol kualitas di jalur perakitan
- Mobil self-driving
- Diagnosa penyakit
- Terjemahan. Untuk buku ini, saya menggunakan layanan terjemahan yang disebut ([DeepL](https://deepl.com)) yang didukung oleh deep neural networks untuk meningkatkan kalimat saya dengan menerjemahkannya dari bahasa Inggris ke bahasa Jerman dan kembali ke bahasa Inggris.
- ...

Terobosan untuk machine learning tidak hanya dicapai melalui komputer yang lebih baik / lebih banyak data / perangkat lunak yang lebih baik, tetapi juga:

**Alat interpretasi mempercepat adopsi machine learning.**

Berdasarkan premis bahwa tujuan model machine learning tidak pernah dapat ditentukan dengan sempurna, maka interpretable machine learning diperlukan untuk menutup kesenjangan antara tujuan yang salah dan tujuan yang sebenarnya.
Di banyak bidang dan sektor, interpretabilitas akan menjadi katalis untuk adopsi machine learning.
Beberapa bukti anekdot:
Banyak orang yang saya ajak bicara tidak menggunakan machine learning karena mereka tidak dapat menjelaskan modelnya kepada orang lain.
Saya percaya bahwa interpretabilitas akan mengatasi masalah ini dan membuat machine learning menarik bagi organisasi dan orang-orang yang menuntut transparansi.
Selain kesalahan spesifikasi masalah, banyak industri memerlukan interpretasi, baik itu karena alasan hukum, karena penghindaran risiko atau untuk mendapatkan wawasan tentang tugas yang mendasarinya.
Machine learning mengotomatiskan proses pemodelan dan memindahkan manusia sedikit lebih jauh dari data dan tugas yang mendasarinya:
Ini meningkatkan risiko masalah dengan desain eksperimental, pilihan distribusi pelatihan, pengambilan sampel, pengkodean data, rekayasa fitur, dan sebagainya.
Alat interpretasi memudahkan untuk mengidentifikasi masalah ini.



## The Future of Interpretability

Mari kita lihat kemungkinan masa depan dari kemampuan interpretasi machine learning.

**Fokusnya adalah pada alat interpretabilitas model-agnostic.**

Jauh lebih mudah untuk mengotomatisasi interpretabilitas ketika dipisahkan dari model machine learning yang mendasarinya.
Keuntungan interpretabilitas model-agnostic terletak pada modularitasnya.
Kami dapat dengan mudah mengganti model machine learning yang mendasarinya.
Kita dapat dengan mudah mengganti metode interpretasi.
Untuk alasan ini, metode model-agnostic akan skala jauh lebih baik.
Itulah mengapa saya percaya bahwa metode model-agnostic akan menjadi lebih dominan dalam jangka panjang.
Tetapi metode yang secara intrinsik dapat ditafsirkan juga akan mendapat tempat.

**Machine learning akan otomatis dan, dengan itu, kemampuan interpretasi.**

Tren yang sudah terlihat adalah otomatisasi pelatihan model.
Itu termasuk rekayasa otomatis dan pemilihan fitur, pengoptimalan hyperparameter otomatis, perbandingan model yang berbeda, dan penggabungan atau penumpukan model.
Hasilnya adalah model prediksi terbaik.
Saat kami menggunakan metode interpretasi model-agnostic, kami dapat secara otomatis menerapkannya ke model apa pun yang muncul dari proses machine learning otomatis.
Di satu sisi, kami juga dapat mengotomatiskan langkah kedua ini:
Secara otomatis menghitung feature importance, partial dependence plot, melatih surrogate models, dan sebagainya.
Tidak ada yang menghentikan Anda untuk secara otomatis menghitung semua interpretasi model ini.
Penafsiran yang sebenarnya masih membutuhkan orang.
Bayangkan: Anda mengunggah kumpulan data, menentukan tujuan prediksi dan dengan menekan satu tombol model prediksi terbaik dilatih dan program mengeluarkan semua interpretasi model.
Sudah ada produk pertama dan saya berpendapat bahwa untuk banyak aplikasi akan cukup menggunakan layanan machine learning otomatis ini.
Saat ini siapa pun dapat membangun situs web tanpa mengetahui HTML, CSS, dan Javascript, tetapi masih banyak pengembang web di sekitarnya.
Demikian pula, saya percaya bahwa setiap orang akan dapat melatih model machine learning tanpa mengetahui cara memprogram, dan masih akan ada kebutuhan akan ahli machine learning.

**Kami tidak menganalisis data, kami menganalisis model.**

Data mentah itu sendiri selalu tidak berguna.
(Saya sengaja melebih-lebihkan.
Kenyataannya adalah Anda membutuhkan pemahaman yang mendalam tentang data untuk melakukan analisis yang bermakna.)
Saya tidak peduli dengan datanya;
Saya peduli dengan pengetahuan yang terkandung dalam data.
Interpretable machine learning adalah cara yang bagus untuk menyaring pengetahuan dari data.
Anda dapat menyelidiki model secara ekstensif, model secara otomatis mengenali jika dan bagaimana fitur relevan untuk prediksi (banyak model memiliki pemilihan fitur bawaan), model dapat secara otomatis mendeteksi bagaimana hubungan direpresentasikan, dan -- jika dilatih dengan benar -- model terakhir adalah pendekatan yang sangat baik dari kenyataan.

Banyak alat analisis sudah didasarkan pada model data (karena didasarkan pada asumsi distribusi):

- Uji hipotesis sederhana seperti Student's t-test.
- Tes hipotesis dengan penyesuaian untuk pembaur (biasanya GLM)
- Analisis Varians (ANOVA)
- correlation coefficient (koefisien linear regression standar terkait dengan correlation coefficient Pearson)
- ...

Apa yang saya katakan di sini sebenarnya bukan hal baru.
Jadi mengapa beralih dari menganalisis model transparan berbasis asumsi ke menganalisis model black box bebas asumsi?
Karena membuat semua asumsi ini bermasalah:
Mereka biasanya salah (kecuali Anda percaya bahwa sebagian besar dunia mengikuti distribusi Gaussian), sulit untuk diperiksa, sangat tidak fleksibel dan sulit untuk diotomatisasi.
Di banyak domain, model berbasis asumsi biasanya memiliki kinerja prediktif yang lebih buruk pada data uji yang tidak tersentuh daripada model machine learning black box.
Ini hanya berlaku untuk kumpulan data besar, karena interpretable models dengan asumsi yang baik sering kali berkinerja lebih baik dengan kumpulan data kecil daripada model black box.
Pendekatan machine learning black box membutuhkan banyak data untuk bekerja dengan baik.
Dengan digitalisasi segalanya, kita akan memiliki kumpulan data yang lebih besar dan oleh karena itu pendekatan machine learning menjadi lebih menarik.
Kami tidak membuat asumsi, kami memperkirakan realitas sedekat mungkin (sambil menghindari overfitting data pelatihan).
Saya berpendapat bahwa kita harus mengembangkan semua alat yang kita miliki dalam statistik untuk menjawab pertanyaan (uji hipotesis, ukuran korelasi, ukuran interaksi, alat visualisasi, confidence intervals, p-value, interval prediksi, distribusi probabilitas) dan menulis ulang untuk model black box .
Di satu sisi, ini sudah terjadi:

- Mari kita ambil model linier klasik: Koefisien regresi standar sudah menjadi ukuran feature importance.
Dengan [ukuran permutation feature importance](#feature-importance), kami memiliki alat yang berfungsi dengan model apa pun.
- Dalam model linier, koefisien mengukur pengaruh fitur tunggal pada hasil yang diprediksi.
Versi umum dari ini adalah [partial dependence plot](#pdp).
- Uji apakah A atau B lebih baik:
Untuk ini kita juga dapat menggunakan fungsi ketergantungan parsial.
Apa yang belum kami miliki (sejauh pengetahuan terbaik saya) adalah uji statistik untuk model black box arbitrer.

**Para ilmuwan data akan mengotomatisasi diri mereka sendiri.**

Saya percaya bahwa ilmuwan data pada akhirnya akan mengotomatisasi diri mereka sendiri dari pekerjaan untuk banyak tugas analisis dan prediksi.
Agar hal ini terjadi, tugas harus didefinisikan dengan baik dan harus ada beberapa proses dan rutinitas di sekitarnya.
Saat ini, rutinitas dan proses ini hilang, tetapi ilmuwan data dan kolega sedang mengerjakannya.
Karena machine learning menjadi bagian integral dari banyak industri dan institusi, banyak tugas akan otomatis.
 
**Robot dan program akan menjelaskan dirinya sendiri.**

Kami membutuhkan antarmuka yang lebih intuitif untuk mesin dan program yang banyak menggunakan machine learning.
Beberapa contoh:
Sebuah mobil self-driving yang melaporkan mengapa berhenti tiba-tiba ("70% kemungkinan bahwa seorang anak akan menyeberang jalan");
Program default kredit yang menjelaskan kepada karyawan bank mengapa aplikasi kredit ditolak ("Pemohon memiliki terlalu banyak kartu kredit dan dipekerjakan dalam pekerjaan yang tidak stabil.");
Lengan robot yang menjelaskan mengapa ia memindahkan barang dari ban berjalan ke tempat sampah ("Itemnya menggila di bagian bawah.").

**Penafsiran dapat meningkatkan penelitian kecerdasan mesin.**

Saya dapat membayangkan bahwa dengan melakukan lebih banyak penelitian tentang bagaimana program dan mesin dapat menjelaskan dirinya sendiri, kita dapat meningkatkan pemahaman kita tentang kecerdasan dan menjadi lebih baik dalam menciptakan mesin yang cerdas.

Pada akhirnya, semua prediksi ini hanyalah spekulasi dan kita harus melihat apa yang sebenarnya terjadi di masa depan.
Bentuk pendapat Anda sendiri dan terus belajar!
