# Acknowledgements

Writing this book was (and still is) a lot of fun.
But it's also a lot of work and I am very happy about the support I received:

A special thanks goes to Verena Haunschmid for contributing the section about [LIME explanations for images](#images-lime).
She works in data science and I recommend following her on Twitter: [\@ExpectAPatronum](https://twitter.com/ExpectAPatronum).
I also want to thank all the [early readers who contributed smaller fixes](https://github.com/christophM/interpretable-ml-book/graphs/contributors) on github!

Further, I want to thank everyone involved in creating illustrations: 
The cover was designed by my friend [\@ArbeitAmText](https://twitter.com/ArbeitAmText). 
The graphics in the [Shapley Value chapter](#shapley) were made by [Abi Aryan](https://twitter.com/GoAbiAryan), using icons made by [Freepik](http://www.freepik.com/) from [Flaticon](www.flaticon.com).
The [awesome images](http://www.chojugiga.com/) in the chapter about the [future of interpretability](#future) are designed by [\@TopeconHeroes](https://twitter.com/topeconheroes).
Verena Haunschmid created the graphic in the [RuleFit chapter](#rulefit).


I am grateful for the funding of my research on interpretable machine learning by the Bavarian State Ministry of Science and the Arts in the framework of the Centre Digitisation.Bavaria (ZD.B).