# Acknowledgements

Writing this book was (and still is) a lot of fun.
But it is also a lot of work and I am very happy about the support I received.

My biggest thank-you goes to Katrin who had the hardest job in terms of hours and effort:
she proofread the book from beginning to end and discovered many spelling mistakes and inconsistencies that I would never have found.
I am very grateful for her support.

A big thank you goes out to all the guest authors.
I was really surprised to learn that people were interested in contributing to the book.
And thanks to their efforts, the contents of the book could be improved!
Tobias Goerke and Magdalena Lang wrote the chapter about Scoped Rules (Anchors).
Fangzhou Li contributed the chapter on Detecting Concepts.
And Susanne Dandl greatly improved the chapter on Counterfactual Examples.
Last but not least, [Verena Haunschmid](https://twitter.com/ExpectAPatronum) wrote the section about LIME explanations for images.
I also want to thank all the readers who provided feedback and contributed corrections directly [on GitHub](https://github.com/christophM/interpretable-ml-book/graphs/contributors)!

Furthermore, I want to thank everyone who created illustrations:
The cover was designed by my friend [\@YvonneDoinel](https://twitter.com/YvonneDoinel).
The graphics in the [Shapley Value chapter](#shapley) were created by [Heidi Seibold](https://twitter.com/HeidiBaya), as well as the turtle example in the [adversarial examples chapter](#adversarial).
Verena Haunschmid created the graphic in the [RuleFit chapter](#rulefit).

I would also like to thank my wife and family who have always supported me.
My wife, in particular, had to listen to me ramble on about the book a lot.
She helped me make many decisions around the writing of the book.

The way I published this book is a bit unconventional.
First, it's not only available as a paperback and ebook, but also as a website, completely free of charge.
The software I used to create this book is called `bookdown`, written by [Yihui Xie](https://yihui.name/), who created many R packages that make it easy to combine R code and text.
Thanks a lot!
I published the book as in-progress book, which has helped me enormously to get feedback and to monetize it along the way.
I would also like to thank you, dear reader, for reading this book without a big publisher name behind it.

I am grateful for the funding of my research on interpretable machine learning by the Bavarian State Ministry of Science and the Arts in the framework of the Centre Digitisation.Bavaria (ZD.B) and by the Bavarian Research Institute for Digital Transformation (bidt).

```{r child = 'impressum.Rmd', eval = is.epub}
```
